FROM nginx
COPY index.html /usr/share/nginx/html/index.html
COPY favicon.ico /usr/share/nginx/html/favicon.ico
COPY css/* /usr/share/nginx/html/css/
COPY images/* /usr/share/nginx/html/images/
COPY js/* /usr/share/nginx/html/js/
COPY nginx.conf /etc/nginx/

